# Polecat Minimal Template - Quick Kubernetes Execution
#
# The simplest Polecat configuration for Kubernetes execution.
# Copy, replace variables, and apply.
#
# For full options, see: polecat-kubernetes.yaml
#
# Variables to replace:
#   {{POLECAT_NAME}} - Unique name (e.g., "furiosa", "nux", "max")
#   {{RIG_NAME}}     - Parent rig (e.g., "athena", "daedalus")
#   {{GIT_REPO}}     - Git repository URL (SSH format)
#   {{GIT_SECRET}}   - Name of git SSH secret
#   {{CLAUDE_SECRET}} - Name of Claude credentials secret
#
# Prerequisites:
#   - Rig exists: kubectl get rig {{RIG_NAME}}
#   - Secrets created (see templates/secret-*.yaml)
#
# Usage:
#   kubectl apply -f - <<EOF
#   apiVersion: gastown.gastown.io/v1alpha1
#   kind: Polecat
#   metadata:
#     name: furiosa
#     namespace: gastown-system
#   spec:
#     rig: athena
#     desiredState: Working
#     taskDescription: "Implement feature X"
#     kubernetes:
#       gitRepository: "git@github.com:org/repo.git"
#       gitSecretRef:
#         name: git-ssh-key
#       claudeCredsSecretRef:
#         name: claude-creds
#   EOF

apiVersion: gastown.gastown.io/v1alpha1
kind: Polecat
metadata:
  name: {{POLECAT_NAME}}
  namespace: gastown-system
spec:
  rig: {{RIG_NAME}}
  desiredState: Working
  taskDescription: "Implement the assigned task"
  kubernetes:
    gitRepository: "{{GIT_REPO}}"
    gitSecretRef:
      name: {{GIT_SECRET}}
    claudeCredsSecretRef:
      name: {{CLAUDE_SECRET}}

---
# Quick start commands:
#
# 1. Create secrets first (see templates/secret-*.yaml)
#    kubectl apply -f secret-git-ssh.yaml
#    kubectl apply -f secret-claude-creds.yaml
#
# 2. Create polecat
#    kubectl apply -f polecat-minimal.yaml
#
# 3. Check status
#    kubectl get polecat {{POLECAT_NAME}} -n gastown-system
#
# 4. View pod logs
#    kubectl logs -f polecat-{{POLECAT_NAME}} -n gastown-system
#
# 5. Terminate when done
#    kubectl patch polecat {{POLECAT_NAME}} -n gastown-system \
#      --type=merge -p '{"spec":{"desiredState":"Terminated"}}'

---
# One-liner examples:
#
# Create working polecat:
#   kubectl apply -f - <<EOF
#   apiVersion: gastown.gastown.io/v1alpha1
#   kind: Polecat
#   metadata:
#     name: furiosa
#     namespace: gastown-system
#   spec:
#     rig: athena
#     desiredState: Working
#     taskDescription: "Fix the authentication bug"
#     kubernetes:
#       gitRepository: "git@github.com:org/repo.git"
#       gitSecretRef:
#         name: git-ssh-key
#       claudeCredsSecretRef:
#         name: claude-creds
#   EOF
#
# Create idle polecat (ready for assignment):
#   kubectl apply -f - <<EOF
#   apiVersion: gastown.gastown.io/v1alpha1
#   kind: Polecat
#   metadata:
#     name: nux
#     namespace: gastown-system
#   spec:
#     rig: athena
#     desiredState: Idle
#     kubernetes:
#       gitRepository: "git@github.com:org/repo.git"
#       gitSecretRef:
#         name: git-ssh-key
#       claudeCredsSecretRef:
#         name: claude-creds
#   EOF
#
# Assign work to idle polecat:
#   kubectl patch polecat nux -n gastown-system --type=merge \
#     -p '{"spec":{"taskDescription":"Implement feature Y","desiredState":"Working"}}'
