# Claude Credentials Secret Template
#
# Contains Claude API credentials for Polecat kubernetes execution.
# Used by: Polecat (kubernetes mode with claudeCredsSecretRef)
#
# Variables to replace:
#   {{SECRET_NAME}}        - Secret name (e.g., "claude-credentials")
#   {{NAMESPACE}}          - Target namespace (e.g., "gastown-system")
#   {{CREDENTIALS_JSON}}   - Base64-encoded ~/.claude/credentials.json
#   {{SETTINGS_JSON}}      - Base64-encoded ~/.claude/settings.json (optional)
#
# Creating the secret (recommended - use kubectl):
#
#   # From existing Claude config (after `claude login`)
#   kubectl create secret generic claude-credentials \
#     --from-file=credentials.json=$HOME/.claude/credentials.json \
#     --from-file=settings.json=$HOME/.claude/settings.json \
#     -n gastown-system
#
#   # Verify
#   kubectl get secret claude-credentials -n gastown-system
#
# Alternative: API key only (headless mode)
#
#   kubectl create secret generic anthropic-api-key \
#     --from-literal=api-key=$ANTHROPIC_API_KEY \
#     -n gastown-system
#
#   Then use `apiKeySecretRef` instead of `claudeCredsSecretRef` in Polecat spec.
#
# Security notes:
#   - Never commit this file with real credentials
#   - Credentials expire - re-run `claude login` if auth fails
#   - Consider separate secrets per team/project for isolation

apiVersion: v1
kind: Secret
metadata:
  name: {{SECRET_NAME}}
  namespace: {{NAMESPACE}}
  labels:
    app.kubernetes.io/name: gastown-operator
    app.kubernetes.io/component: credentials
type: Opaque
data:
  # Base64-encoded credentials.json (REQUIRED)
  # Generate with: base64 -i ~/.claude/credentials.json
  credentials.json: {{CREDENTIALS_JSON}}

  # Base64-encoded settings.json (OPTIONAL)
  # Generate with: base64 -i ~/.claude/settings.json
  # settings.json: {{SETTINGS_JSON}}

---
# Alternative: API Key Secret (for headless usage)
#
# apiVersion: v1
# kind: Secret
# metadata:
#   name: anthropic-api-key
#   namespace: gastown-system
# type: Opaque
# stringData:
#   api-key: "sk-ant-api03-..."
#
# Reference in Polecat:
#   spec:
#     kubernetes:
#       apiKeySecretRef:
#         name: anthropic-api-key
#         key: api-key

---
# Imperative creation (RECOMMENDED)
#
# Option 1: Full OAuth credentials (interactive login support)
# kubectl create secret generic claude-credentials \
#   --from-file=credentials.json=$HOME/.claude/credentials.json \
#   -n gastown-system
#
# Option 2: API key only (headless, no OAuth refresh)
# kubectl create secret generic anthropic-api-key \
#   --from-literal=api-key="$ANTHROPIC_API_KEY" \
#   -n gastown-system

---
# Troubleshooting
#
# "authentication failed" errors:
#   1. Check secret exists: kubectl get secret claude-credentials -n gastown-system
#   2. Verify credentials.json present: kubectl get secret claude-credentials -o jsonpath='{.data}' | jq 'keys'
#   3. Re-login if expired: claude login
#   4. Update secret: kubectl delete secret claude-credentials -n gastown-system && (create new)
