# Git SSH Secret Template
#
# Contains SSH private key for git clone/push operations.
# Used by: Polecat (kubernetes mode), Refinery, BeadStore
#
# Variables to replace:
#   {{SECRET_NAME}}      - Secret name (e.g., "git-credentials")
#   {{NAMESPACE}}        - Target namespace (e.g., "gastown-system")
#   {{SSH_PRIVATE_KEY}}  - Base64-encoded SSH private key
#
# Creating the secret (recommended - use kubectl):
#
#   # Generate key pair if needed
#   ssh-keygen -t ed25519 -C "gastown-operator" -f ./gastown-git-key -N ""
#
#   # Create secret directly (preferred)
#   kubectl create secret generic git-credentials \
#     --from-file=ssh-privatekey=./gastown-git-key \
#     -n gastown-system
#
#   # Add public key to GitHub/GitLab (with write access)
#   cat ./gastown-git-key.pub
#
#   # Clean up local files
#   rm ./gastown-git-key ./gastown-git-key.pub
#
# If you must use this YAML template:
#   1. Base64 encode your private key: base64 -i ~/.ssh/id_ed25519
#   2. Replace {{SSH_PRIVATE_KEY}} with the output
#   3. Apply: kubectl apply -f secret-git-ssh.yaml
#
# Security notes:
#   - Never commit this file with real keys
#   - Use deploy keys with minimal permissions (single repo)
#   - Rotate keys every 90 days

apiVersion: v1
kind: Secret
metadata:
  name: {{SECRET_NAME}}
  namespace: {{NAMESPACE}}
  labels:
    app.kubernetes.io/name: gastown-operator
    app.kubernetes.io/component: credentials
type: kubernetes.io/ssh-auth
data:
  # Base64-encoded SSH private key
  # Generate with: base64 -i ~/.ssh/id_ed25519
  ssh-privatekey: {{SSH_PRIVATE_KEY}}

---
# Alternative: Create secret imperatively (RECOMMENDED)
#
# kubectl create secret generic git-credentials \
#   --from-file=ssh-privatekey=$HOME/.ssh/gastown-deploy-key \
#   -n gastown-system
#
# This avoids having base64 keys in version control.

---
# Required: Add public key to Git provider
#
# GitHub:
#   1. Go to repository Settings -> Deploy keys
#   2. Add new deploy key with "Allow write access" checked
#
# GitLab:
#   1. Go to project Settings -> Repository -> Deploy keys
#   2. Add key with "Write" permission
#
# Verify:
#   ssh -i ./gastown-git-key -T git@github.com
